### ISSUE TITLE
Video Player Changes

### ISSUE THREAD

**Issue by bevanjkay** [Myles-Trevino/Echo360-Downloader#2]
Hi Myles,
Not sure if you're seeing the same now, but for my videos the page is now returning the mp4 URL instead of the m3u8 playlist URL. It seems that Echo360 have changed the player again.

**Comment by bevanjkay** [comment]
It looks like a conventional browser extension video downloader can grab the videos with the updated system.

**Comment by Myles-Trevino** [comment]
It seems the ones I need still use HLS, so perhaps what you're saying only applies to some videos. Could you post a link to one of those videos for reference?
